#
# Development environment settings.
#
export ANT_HOME=/usr/local/apache-ant-1.9.4
export M2_HOME=/usr/local/apache-maven/apache-maven-3.1.1
export M2=$M2_HOME/bin
export MAVEN_OPTS=" -Xms256m -Xmx512m"
export JAVA_HOME=/usr/local/jdk1.7.0_51
export PG_HOME=/opt/PostgreSQL/9.3
export PATH=$PATH:$JAVA_HOME/bin:$ANT_HOME/bin:$M2:$PG_HOME/bin

# Color ls extra -- show directories as light blue
export LS_COLORS='di=94'
